#!/usr/bin/env bash

ARGS="$@"
DIR=$(dirname "$0")
SCRIPT="${DIR}/mngr.R"
jobids=$(nice -n 19 Rscript --no-init-file "$SCRIPT" "$ARGS")
result=$?
if [ $result -eq 0 ]; then
    if [ -n "$jobids" ]; then
        echo "$jobids"
        jobids=$(echo "$jobids" | tail -1)
        mngr-monitor "$jobids"
    fi
fi
