#!/usr/bin/env bash

jobids=$(nice -n 19 Rscript --no-init-file -e "source(\"~/.mngr/config.R\"); library(mngr, quietly = TRUE, warn.conflicts = FALSE); mngr:::run_cmd(args = commandArgs(TRUE))" --args $1)
result=$?
if [ $result -eq 0 ]; then
    if [ -n "$jobids" ]; then
        echo "$jobids"
        jobids=$(echo "$jobids" | tail -1)
        mngr-monitor "$jobids"
    fi
fi
