#!/usr/bin/env bash

Rscript --no-init-file -e "library(mngr, quietly = T, warn.conflicts = FALSE); source(\"~/.mngr/config.R\"); options(width = as.integer(system(\"tput cols\", intern = TRUE))); latest_logs(filter = TRUE)"
